### ISSUE TITLE
Docker Build Error

### ISSUE THREAD

**Issue by jjackevans** [shoyo/acoustic-keylogger#11]
Hi,

I am attempting to build using the Dockerfile and am receiving the following error.
I am using docker-compose version 1.27.4, build 40524192 on powershell.

 `$  docker-compose build
db uses an image, skipping
Building env
Step 1/6 : FROM python:3.6.8
3.6.8: Pulling from library/python
6f2f362378c5: Pull complete                                                                                                           494c27a8a6b8: Pull complete                                                                                                           7596bb83081b: Pull complete                                                                                                           372744b62d49: Pull complete                                                                                                           615db220d76c: Pull complete                                                                                                           1865698adfb0: Pull complete                                                                                                           7159b3304cc0: Pull complete                                                                                                           ad0713808ef6: Pull complete                                                                                                           7ba593904573: Pull complete                                                                                                           Digest: sha256:f20a9bfddd87c238c3d2316b4179222f219090cbb25d5b6975070d4dd4b75004
Status: Downloaded newer image for python:3.6.8
 ---> 48c06762acf0
Step 2/6 : WORKDIR /env
 ---> Running in 2bd370ce882b
Removing intermediate container 2bd370ce882b
 ---> c42167308e2b
Step 3/6 : COPY requirements.txt /env/
 ---> 72fc53d72c5f
Step 4/6 : RUN pip install -r requirements.txt
 ---> Running in 97d6d3926868
Collecting hmmlearn==0.2.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d7/c5/91b43156b193d180ed94069269bcf88d3c7c6e54514a8482050fa9995e10/hmmlearn-0.2.2.tar.gz (146kB)
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-orjm8t0p/numpy-1.20.0/setup.py", line 30, in <module>
        self.distribution.ext_modules[:] = cythonize("**/*.pyx")
    RuntimeError: Python version >= 3.7 required.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-aludejsd/hmmlearn/setup.py", line 98, in <module>
        "gui_scripts": [],
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-orjm8t0p/numpy-1.20.0/setup.py", line 30, in <module>
        self.distribution.ext_modules[:] = cythonize("**/*.pyx")
    RuntimeError: Python version >= 3.7 required.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-aludejsd/hmmlearn/
WARNING: You are using pip version 19.1.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'env' failed to build : The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1`

**Comment by shoyo** [comment]
Hi @jjackevans, thanks for the heads up!
This repo was my university research project and I've since moved on, so I apologize that the build instructions were out-of-date.

I've updated both the dependencies and instructions in [the latest PR](#12), so `docker-compose build` and `docker-compose up` should work as intended now. In the future, just edit the config as stated in the error to resolve any dependency issues.
